name: dropzonebuilder
description: A new Flutter project.
version: 0.0.1
homepage: https://github.com/Patrick386/dropzone_builder

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^1.0.3
  flutter_dropzone: ^3.0.5
  freezed_annotation: any


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: any
  freezed: any
  # Used by tests. Not required to use `json_serializable`.
  # Used by tests. Not required to use `json_serializable`.
  build_verify: ^3.0.0


flutter:
  uses-material-design: true
